In [22]:
import cv2
import numpy as np
import dlib
def extract_index_nparray(nparray):
    index = None
    for num in nparray[0]:
        index = num
        break
    return index

In [23]:
img = cv2.imread("bradley_cooper.jpg")
img2 = cv2.imread("jim_carrey.jpg")
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
mask = np.zeros_like(img_gray)

In [3]:
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")

In [4]:
faces = detector(img_gray)
for face in faces:
    landmarks = predictor(img_gray, face)
    landmarks_points = []
    for n in range(0, 68):
        x = landmarks.part(n).x
        y = landmarks.part(n).y
        landmarks_points.append((x, y))

In [5]:
points = np.array(landmarks_points, np.int32)
convexhull = cv2.convexHull(points)
cv2.polylines(img, [convexhull], True, (255, 0, 0), 3)


array([[[31, 71, 53],
        [29, 69, 51],
        [28, 66, 48],
        ...,
        [ 0, 19,  7],
        [ 8, 30, 18],
        [14, 36, 24]],

       [[31, 69, 51],
        [29, 67, 49],
        [25, 63, 45],
        ...,
        [ 7, 24, 13],
        [13, 33, 21],
        [16, 38, 26]],

       [[28, 64, 47],
        [25, 61, 44],
        [21, 57, 40],
        ...,
        [14, 30, 19],
        [18, 35, 24],
        [18, 38, 26]],

       ...,

       [[21,  6,  4],
        [19,  4,  2],
        [21,  4,  1],
        ...,
        [53, 24, 10],
        [56, 27, 13],
        [59, 29, 18]],

       [[22,  7,  5],
        [21,  6,  4],
        [23,  6,  3],
        ...,
        [60, 31, 17],
        [54, 25, 11],
        [51, 21, 10]],

       [[20,  5,  3],
        [20,  5,  3],
        [22,  5,  2],
        ...,
        [66, 37, 23],
        [60, 31, 17],
        [56, 26, 15]]], dtype=uint8)

In [6]:
mask = np.zeros_like(img_gray)

In [7]:
cv2.fillConvexPoly(mask, convexhull, 255)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [8]:
face_image_1 = cv2.bitwise_and(img, img, mask=mask)

In [ ]:
cv2.imshow("Image 1", img)
cv2.imshow("Face image 1", face_image_1)
cv2.imshow("Mask", mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
# Delaunay triangulation
rect = cv2.boundingRect(convexhull)
subdiv = cv2.Subdiv2D(rect)
subdiv.insert(landmarks_points)
triangles = subdiv.getTriangleList()
triangles = np.array(triangles, dtype=np.int32)
indexes_triangles = []
for t in triangles:
        pt1 = (t[0], t[1])
        pt2 = (t[2], t[3])
        pt3 = (t[4], t[5])
cv2.line(img, pt1, pt2, (0, 0, 255), 2)
cv2.line(img, pt2, pt3, (0, 0, 255), 2)
cv2.line(img, pt1, pt3, (0, 0, 255), 2)        

array([[[31, 71, 53],
        [29, 69, 51],
        [28, 66, 48],
        ...,
        [ 0, 19,  7],
        [ 8, 30, 18],
        [14, 36, 24]],

       [[31, 69, 51],
        [29, 67, 49],
        [25, 63, 45],
        ...,
        [ 7, 24, 13],
        [13, 33, 21],
        [16, 38, 26]],

       [[28, 64, 47],
        [25, 61, 44],
        [21, 57, 40],
        ...,
        [14, 30, 19],
        [18, 35, 24],
        [18, 38, 26]],

       ...,

       [[21,  6,  4],
        [19,  4,  2],
        [21,  4,  1],
        ...,
        [53, 24, 10],
        [56, 27, 13],
        [59, 29, 18]],

       [[22,  7,  5],
        [21,  6,  4],
        [23,  6,  3],
        ...,
        [60, 31, 17],
        [54, 25, 11],
        [51, 21, 10]],

       [[20,  5,  3],
        [20,  5,  3],
        [22,  5,  2],
        ...,
        [66, 37, 23],
        [60, 31, 17],
        [56, 26, 15]]], dtype=uint8)

In [17]:
def extract_index_nparray(nparray):
    index = None
    for num in nparray[0]:
        index = num
        break
    return index

In [19]:
index_pt1 = np.where((points == pt1).all(axis=1))
index_pt1 = extract_index_nparray(index_pt1)
index_pt2 = np.where((points == pt2).all(axis=1))
index_pt2 = extract_index_nparray(index_pt2)
index_pt3 = np.where((points == pt3).all(axis=1))
index_pt3 = extract_index_nparray(index_pt3)



In [26]:
if index_pt1 is not None and index_pt2 is not None and index_pt3 is not None:
            triangle = [index_pt1, index_pt2, index_pt3]
            indexes_triangles.append(triangle)

In [27]:
# Face 2
faces2 = detector(img2_gray)
for face in faces2:
    landmarks = predictor(img2_gray, face)
    landmarks_points = []
    for n in range(0, 68):
        x = landmarks.part(n).x
        y = landmarks.part(n).y
        landmarks_points.append((x, y))
        cv2.circle(img2, (x, y), 3, (0, 255, 0), -1)

In [ ]:
cv2.imshow("Image 1", img)
cv2.imshow("Face image 1", face_image_1)
cv2.imshow("image2", img2)
cv2.imshow("Mask", mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# Triangulation of both faces
for triangle_index in indexes_triangles:
    # Triangulation of the first face
    tr1_pt1 = landmarks_points[triangle_index[0]]
    tr1_pt2 = landmarks_points[triangle_index[1]]
    tr1_pt3 = landmarks_points[triangle_index[2]]
    triangle1 = np.array([tr1_pt1, tr1_pt2, tr1_pt3], np.int32)
    rect1 = cv2.boundingRect(triangle1)
    (x, y, w, h) = rect1
    cropped_triangle = img[y: y + h, x: x + w]
    cropped_tr1_mask = np.zeros((h, w), np.uint8)
    points = np.array([[tr1_pt1[0] - x, tr1_pt1[1] - y],
                      [tr1_pt2[0] - x, tr1_pt2[1] - y],
                      [tr1_pt3[0] - x, tr1_pt3[1] - y]], np.int32)
    cv2.fillConvexPoly(cropped_tr1_mask, points, 255)
    cropped_triangle = cv2.bitwise_and(cropped_triangle, cropped_triangle,
                                       mask=cropped_tr1_mask)

    cv2.line(img, tr1_pt1, tr1_pt2, (0, 0, 255), 2)
    cv2.line(img, tr1_pt3, tr1_pt2, (0, 0, 255), 2)
    cv2.line(img, tr1_pt1, tr1_pt3, (0, 0, 255), 2)

In [ ]:
    # Triangulation of second face
    tr2_pt1 = landmarks_points2[triangle_index[0]]
    tr2_pt2 = landmarks_points2[triangle_index[1]]
    tr2_pt3 = landmarks_points2[triangle_index[2]]
    triangle2 = np.array([tr2_pt1, tr2_pt2, tr2_pt3], np.int32)
    rect2 = cv2.boundingRect(triangle2)
    (x, y, w, h) = rect2
    cropped_triangle2 = img2[y: y + h, x: x + w]
    cropped_tr2_mask = np.zeros((h, w), np.uint8)
    points2 = np.array([[tr2_pt1[0] - x, tr2_pt1[1] - y],
                       [tr2_pt2[0] - x, tr2_pt2[1] - y],
                       [tr2_pt3[0] - x, tr2_pt3[1] - y]], np.int32)
    cv2.fillConvexPoly(cropped_tr2_mask, points2, 255)
    cropped_triangle2 = cv2.bitwise_and(cropped_triangle2, cropped_triangle2,
                                       mask=cropped_tr2_mask)
    cv2.line(img2, tr2_pt1, tr2_pt2, (0, 0, 255), 2)
    cv2.line(img2, tr2_pt3, tr2_pt2, (0, 0, 255), 2)
    cv2.line(img2, tr2_pt1, tr2_pt3, (0, 0, 255), 2)

In [ ]:
# Warp triangles
points = np.float32(points)
points2 = np.float32(points2)
M = cv2.getAffineTransform(points, points2)
warped_triangle = cv2.warpAffine(cropped_triangle, M, (w, h))
break    

In [ ]:
cv2.imshow("Image 1", img)
cv2.imshow("image2", img2)
cv2.imshow("cropped triangle 1", cropped_triangle)
cv2.imshow("cropped triangle 2", cropped_triangle2)
cv2.imshow("Warped triangle", warped_triangle)
cv2.waitKey(0)
cv2.destroyAllWindows()